   stages:
     - build
     - test
   build_job:
     tags:
       - shared
     stage: build
     only:
       - master
       - develop

     script:
       - echo "Проект собрался"

   test_job:
     tags:
       - shared
     stage: test

     script:
       - echo "Тест прошел!"

   test_unit_job:
     tags:
       - shared
     stage: test

     script:
       - echo "Unit tests!"
    when: manual

